[libgpg-error] Update gpgrt-config patch

diff --git a/ports/libgpg-error/gpgrt-config.patch b/ports/libgpg-error/gpgrt-config.patch
--- a/ports/libgpg-error/gpgrt-config.patch
+++ b/ports/libgpg-error/gpgrt-config.patch
@@ -1,31 +1,36 @@
 diff --git a/src/gpgrt-config.in b/src/gpgrt-config.in
-index bada0f2..82efac5 100644
+index bada0f2..e774751 100644
 --- a/src/gpgrt-config.in
 +++ b/src/gpgrt-config.in
-@@ -166,7 +166,7 @@ read_config_file () {
+@@ -132,7 +132,6 @@ EOF2
+ 		*:|*:\ ) ;;
+ 		*)
+ 		    echo "Error reading $_filename: $_line" 1>&2
+-		    exit 1
+ 		    ;;
+ 	    esac
+ 	fi
+@@ -166,6 +165,7 @@ read_config_file () {
  	fi
  	exit 1
      fi
--    read_config_from_stdin $RESULT < $RESULT
-+    VAR_pcfiledir="${RESULT%/*}" read_config_from_stdin $RESULT < $RESULT
++    VAR_pcfiledir="${RESULT%/*}" \
+     read_config_from_stdin $RESULT < $RESULT
  }
  
- cleanup_vars_attrs () {
-@@ -458,8 +458,11 @@ determine_gpgrt_libdir () {
-     GPGRT_CONFIG="$0"
-     #
-     # Get the prefix of gpgrt-config assuming it's something like:
--    #   <PREFIX>/bin/gpgrt-config
--    gpgrt_prefix=${GPGRT_CONFIG%/*/*}
-+    #   <PREFIX>/tools/libgpg-error[/debug]/bin/gpgrt-config
-+    case "$GPGRT_CONFIG" in
-+    */debug/bin/gpgrt-config) gpgrt_prefix=${GPGRT_CONFIG%/*/*/*/*/*} ;;
-+    *)                        gpgrt_prefix=${GPGRT_CONFIG%/*/*/*/*} ;;
-+    esac
-     possible_libdir1=${gpgrt_prefix}/lib
-     # Determine by using system libdir-format with CC, it's like:
-     #   Normal style: /usr/lib
-@@ -598,7 +601,8 @@ output=""
+@@ -540,6 +540,11 @@ while test $# -gt 0; do
+ 	    ;;
+     esac
+ done
++vcpkg_prefix=$(echo "$0" | sed -e 's,^\([a-zA-Z]\):/,/\1/,')
++case "$vcpkg_prefix" in
++*/tools/libgpg-error/debug/bin/gpgrt-config)  libdir="${vcpkg_prefix%/*/*/*/*/*}/debug/lib" ;;
++*/tools/libgpg-error/bin/gpgrt-config)        libdir="${vcpkg_prefix%/*/*/*/*}/lib" ;;
++esac
+ 
+ if env | grep '^PKG_CONFIG_LIBDIR=$' >/dev/null 2>&1; then
+   # The variable set as empty, we use PKG_CONFIG_PATH in this case,
+@@ -598,7 +603,8 @@ output=""
  
  mt="no"
  
